name: Test PRs

on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
    - name: Test YAML file syntax
      run: |
        yamllint -c yaml-rules.yaml translations/*/*.yml
        yamllint -c yaml-rules.yaml indicator-config/*.yml
        yamllint -c yaml-rules.yaml meta/*.yml
        yamllint -c yaml-rules.yaml _prose.yml
        yamllist -c yaml-rules.yaml config_data.yml
    - name: Test and build data
      run: |
        python scripts/check_data.py
        python scripts/build_data.py
